# The Arrs Stack - youtube.com/@KLTechVideos
# Gluetun - QB - Prowlarr - Sonarr - Radarr - Jellyseerr
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - ${STACKS_PATH}/arrs/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=true
      - SERVER_REGIONS=${SERVER_REGIONS}
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8080:8080/tcp # qb      
      - 9696:9696/tcp # prowlarr
      - 7878:7878/tcp # radarr
      - 8989:8989/tcp # sonarr
      - 5055:5055/tcp # jellyseer
      - 8191:8191/tcp # flaresolverr
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.qb.entrypoints=web
      - traefik.http.routers.qb.rule=Host(`qb.home`)
      - traefik.http.services.qb.loadbalancer.server.port=8080
      - traefik.http.routers.prowlarr.entrypoints=web
      - traefik.http.routers.prowlarr.rule=Host(`prowlarr.home`)
      - traefik.http.services.prowlarr.loadbalancer.server.port=9696
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`rad.home`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.rule=Host(`son.home`)
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.js.entrypoints=web
      - traefik.http.routers.js.rule=Host(`js.home`)
      - traefik.http.services.js.loadbalancer.server.port=5055
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${STACKS_PATH}/arrs/qbit:/config
      - ${DOWNLOADS_PATH}:/data/downloads
    restart: always
    network_mode: service:gluetun
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080
      interval: 15s # Check every 15 seconds
      timeout: 15s # Timeout if the check takes more than 14 seconds
      retries: 8 # Retry up to 5 times before marking the service unhealthy
      start_period: 15s # Wait 10 seconds before starting the first health check
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest # Change to "latest" for stable
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/arrs/prowlarr/Config:/config
      - ${STACKS_PATH}/arrs/prowlarr/Backup:/data/Backup
      - ${DOWNLOADS_PATH}:/data/downloads
    restart: unless-stopped
    network_mode: service:gluetun
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped
    network_mode: service:gluetun
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest # Change to "latest" for stable
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/arrs/sonarr/Config:/config
      - ${STACKS_PATH}/arrs/sonarr/Backup:/data/Backup
      - ${TV_PATH}:/data/tvshows
      - ${DOWNLOADS_PATH}:/data/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    #depends_on:
    #  qbittorrent:
    #    condition: service_healthy
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/arrs/radarr/Config:/config
      - ${MOVIES_PATH}:/data/movies
      - ${DOWNLOADS_PATH}:/data/downloads
      - ${STACKS_PATH}/arrs/radarr/Backup:/data/Backup
    restart: unless-stopped
    network_mode: service:gluetun
    #depends_on:
    #  qbittorrent:
    #    condition: service_healthy
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/arrs/jellyseerr:/app/config
    restart: unless-stopped
    network_mode: service:gluetun
    #depends_on:
    #  qbittorrent:
    #    condition: service_healthy
networks:
  proxy:
    external: true
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 173.25.0.0/16
          gateway: 173.25.0.1
