# Push from Komodo 🦎
services:
  dockge:
    image: louislam/dockge
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STACKS_PATH}/dockge/data:/app/data
      - ${STACKS_PATH}:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
    labels:
      - traefik.enable=true
      - traefik.http.routers.dockge.entrypoints=web
      - traefik.http.routers.dockge.rule=Host(`dockge.home`)
networks:
  default:
    name: proxy
    external: true
