services:
  dockge:
    image: louislam/dockge
    container_name: dockge
    hostname: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - ${STACKS_PATH}:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
networks:
  default:
    name: proxy
    external: true
