services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.0.5
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
      #- CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_PASSWORD}
    volumes:
      - ${STACKS_PATH}/duplicati/config:/config
      - ${BACKUP_PATH}:/backups
      - ${STACKS_PATH}:/source
    ports:
      - 8200:8200
    restart: unless-stopped
networks:
  default:
    name: proxy
    external: true
