#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.      #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${STACKS_PATH}/homarr/appdata:/appdata
    environment:
      SECRET_ENCRYPTION_KEY: ${SECRET_ENCRYPTION_KEY}
    ports:
      - '7575:7575'
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.entrypoints=web
      - traefik.http.routers.homarr.rule=Host(`${HOST_DOMAIN}`)
      # - traefik.http.routers.homarr.tls=true
      # - traefik.http.routers.homarr.tls.certresolver=cloudflare
networks:
  default:
    name: proxy
    external: true
