services:
  homepage:
    image: ghcr.io/gethomepage/homepage
    container_name: homepage
    environment:
      # (Required) See https://gethomepage.dev/installation/#homepage_allowed_hosts
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS:?HOMEPAGE_ALLOWED_HOSTS not set}
      - LOG_LEVEL=info
    # (Optional) Run as a specific user
      - PUID=1000
      - PGID=1000
    ports:
      - 5005:3000
    volumes:
      - ${STACKS_PATH}/homepage/config:/app/config
#      - ./images:/app/images  # for custom background images
#      - ./icons:/app/icons  # for custom icons
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.rule=Host(`home.esh.racer.red`)
      - traefik.http.routers.homepage.tls=true
      - traefik.http.services.homepage.loadbalancer.server.port=5005
#   (Optional) For secure docker socket integration
#   dockerproxy:
#     image: ghcr.io/tecnativa/docker-socket-proxy:0.3.0
#     container_name: homepage-demo-1-dockerproxy
#     environment:
#       - CONTAINERS=1 # Allow access to viewing containers
#       - SERVICES=1 # Allow access to viewing services (necessary when using Docker Swarm)
#       - TASKS=1 # Allow access to viewing tasks (necessary when using Docker Swarm)
#       - POST=0 # Disallow any POST operations (effectively read-only)
#     ports:
#       - 127.0.0.1:2375:2375
#     volumes:
#       - /run/docker.sock:/run/docker.sock:ro # Mounted as read-only
#     restart: unless-stopped
