services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    networks:
      arrs_arrs:
        ipv4_address: 173.25.0.41
      default: null
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${STACKS_PATH}/jelly:/config
      - ${MEDIA_PATH}/tvshows:/data/tvshows
      - ${MEDIA_PATH}/movies:/data/movies
    ports:
      - 8096:8096
      - 7359:7359
      - 1900:1900
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
networks:
  arrs_arrs:
    external: true
  default:
    name: proxy
    external: true
