services:
  traefik:
    image: docker.io/library/traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 9090:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ${STACKS_PATH}/traefik/config:/etc/traefik:ro
      - ${STACKS_PATH}/traefik/certs:/var/traefik/certs
    #environment:
    #- CF_DNS_API_TOKEN=your-cloudflare-api-token  # <-- Change this to your Cloudflare API Token
    networks:
      static:
        ipv4_address: 172.7.7.5
      default: null
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.home`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
networks:
  default:
    name: proxy
    external: true
  static:
    external: true
