services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:2.2.0
    container_name: duplicati
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Europe/Madrid
      - SETTINGS_ENCRYPTION_KEY=${DUPLICATI_ENCRYPTION_KEY}
      #- CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${DUPLICATI_PASSWORD}
      - DOCKER_MODS=linuxserver/mods:universal-docker
    volumes:
      - ${STACKS_PATH}/duplicati/config:/config
      - ${BACKUP_PATH}:/backups
      - ${RESTORE_PATH}:/restore
      - ${STACKS_PATH}:/source:ro
      - ${STACKS_PATH}/duplicati/scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8200:8200
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.duplicati.entrypoints=websecure
      - traefik.http.routers.duplicati.rule=Host(`${DUPLICATI_HOST}`)
      - traefik.http.routers.duplicati.tls=true
networks:
  default:
    name: proxy
    external: true
